# -*- coding: utf-8 -*-
"""
Created on Mon Jul 24 17:33:14 2017

@author: Aster
"""

def ProjectEuler_problem2(N):
    """
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    find the sum of the even-valued terms.
    """
    f1,f2 = 1,2
    f3 = 1
    my_sum = 2
    while f3 <= N:
        f3 = f1 + f2
        if f3 % 2 == 0:
            my_sum += f3
        f1 = f2
        f2 = f3
    print('ans_P2 = ',my_sum)

ProjectEuler_problem2(4000000)
