#By Matthew Schieber

a2: assignment2.cc timer.cc 
	icpc -qopenmp assignment2.cc timer.cc -o a2

a3: assignment3.cc timer.cc 
	icpc -qopenmp assignment3.cc timer.cc -o a3

a4: assignment4.cc timer.cc
	icpc -qopenmp assignment4.cc timer.cc -o a4 -lblas
	
 

clean:
	rm -f *.o a2 a3
